<!DOCTYPE html>
<html>
<head>
    <title>Digital Clock</title>
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        
        .clock {
            font-size: 80px;
        }
    </style>
</head>
<body>
    <div class="clock">
        <span id="time"></span>
    </div>
    <script>
        function updateTime() {
            const now = new Date();
            const hours = now.getHours().toString().padStart(2, '0');
            const minutes = now.getMinutes().toString().padStart(2, '0');
            const seconds = now.getSeconds().toString().padStart(2, '0');
            const timeString = `${hours}:${minutes}:${seconds}`;
            document.getElementById('time').textContent = timeString;
        }

        // Update the time every second
        setInterval(updateTime, 1000);

        // Initial call to set the time immediately
        updateTime();
    </script>
</body>
</html>
